// <auto-generated />
using System;
using HelpDeskApp.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HelpDeskApp.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211120002054_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HelpDeskApp.Dominio.Ambiente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AmbNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AmbUbicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ambientes");
                });

            modelBuilder.Entity("HelpDeskApp.Dominio.Empleados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmpApellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpCelular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpCorreo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpNombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoEmpleado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("HelpDeskApp.Dominio.Incidentes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmpDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IncFechaAtencion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IncFechaReporte")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Incidentes");
                });

            modelBuilder.Entity("HelpDeskApp.Dominio.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AmbienteId")
                        .HasColumnType("int");

                    b.Property<string>("InCantidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoElemento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("HelpDeskApp.Dominio.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EmpleadosId")
                        .HasColumnType("int");

                    b.Property<string>("LogPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadosId");

                    b.ToTable("Lo");
                });

            modelBuilder.Entity("HelpDeskApp.Dominio.MantenimientoCorrectivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AmbienteId")
                        .HasColumnType("int");

                    b.Property<int?>("IncidentesId")
                        .HasColumnType("int");

                    b.Property<string>("ManDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ManFechaSolucion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.HasIndex("IncidentesId");

                    b.ToTable("MantenimientoCorrectivos");
                });

            modelBuilder.Entity("HelpDeskApp.Dominio.MantenimientoPreventivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AmbienteId")
                        .HasColumnType("int");

                    b.Property<string>("ManPDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ManPFecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.ToTable("MantenimientoPreventivos");
                });

            modelBuilder.Entity("HelpDeskApp.Dominio.Inventario", b =>
                {
                    b.HasOne("HelpDeskApp.Dominio.Ambiente", "Ambiente")
                        .WithMany()
                        .HasForeignKey("AmbienteId");

                    b.Navigation("Ambiente");
                });

            modelBuilder.Entity("HelpDeskApp.Dominio.Login", b =>
                {
                    b.HasOne("HelpDeskApp.Dominio.Empleados", "Empleados")
                        .WithMany()
                        .HasForeignKey("EmpleadosId");

                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("HelpDeskApp.Dominio.MantenimientoCorrectivo", b =>
                {
                    b.HasOne("HelpDeskApp.Dominio.Ambiente", "Ambiente")
                        .WithMany()
                        .HasForeignKey("AmbienteId");

                    b.HasOne("HelpDeskApp.Dominio.Incidentes", "Incidentes")
                        .WithMany()
                        .HasForeignKey("IncidentesId");

                    b.Navigation("Ambiente");

                    b.Navigation("Incidentes");
                });

            modelBuilder.Entity("HelpDeskApp.Dominio.MantenimientoPreventivo", b =>
                {
                    b.HasOne("HelpDeskApp.Dominio.Ambiente", "Ambiente")
                        .WithMany()
                        .HasForeignKey("AmbienteId");

                    b.Navigation("Ambiente");
                });
#pragma warning restore 612, 618
        }
    }
}
